from tests.architectures.fixtures.layer import FCLayer, ACTLayer


class TestPerceptron:
    def test_creation_with_correct_args(self): ...
    def test_creation_with_incorrect_args(self): ...
    def test_passing_through_perceptron(self): ...
    def test_passing_after_serialization_const(self): ...
    def test_passing_after_serialization_random(self): ...
    def test_backpropagation(self): ...
